version: 2.1
jobs:
  plan:
    docker:
      - image: public.ecr.aws/hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: terraform init
          command: |
            export $AWS_ACCESS_KEY_ID
            export $AWS_DEFAULT_REGION
            export $AWS_SECRET_ACCESS_KEY
            terraform init tf/
            terraform plan tf/
workflows:
  plan:
    jobs:
      - plan


