apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: app-jm
  name: ingress-app-jm
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-app-jm
                port: 
                  number: 80
